language: cpp

compiler:
 - gcc

notifications:
  recipients:
    - luca.bonifacio@bbv.ch
  email:
    on_success: change
    on_failure: always

# 
# Needs to install Qt5 before
# 
before_install:
 - lsb_release -a
 - sudo apt-add-repository --yes ppa:canonical-qt5-edgers/qt5-proper
 - sudo apt-get update -qq
 - sudo apt-get install -qq qtdeclarative5-dev qt5-default qtdeclarative5-qtquick2-plugin qtdeclarative5-test-plugin
 - sudo apt-get install -qq g++-4.8 xvfb
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.8
  - sudo pip install cpp-coveralls --use-mirrors

#
# By default Travis CI will run:
#   ./configure && make && make test
# to compile your project and run the tests. It is possible to override
# this behavior by specifying your own install: and script: commands.
# 

script: "qmlscene NoteApp/NoteApp.qml"
