language: cpp

compiler:
 - gcc

notifications:
  recipients:
    - luca.bonifacio@bbv.ch
  email:
    on_success: change
    on_failure: always

before_install:
 - lsb_release -a
 - sudo apt-add-repository --yes ppa:canonical-qt5-edgers/qt5-proper
 - sudo apt-get update
 - sudo apt-get install qtdeclarative5-dev

#
# By default Travis CI will run:
#   ./configure && make && make test
# to compile your project and run the tests. It is possible to override
# this behavior by specifying your own install: and script: commands.
# 

script: "qmlscene NoteApp/NoteApp.qml"
